Question 2: Number of columns in the dataset 

In [1]:
import pandas as pd
import numpy as np

pandas_version = pd.__version__

print( 'Pandas version = ' + pandas_version + '\n' )

df = pd.read_csv('housing.csv')

# computing number of rows
rows = len(df.axes[0])
 
# computing number of columns
cols = len(df.axes[1])
 
print(df)
print("Number of Rows: ", rows)
print("Number of Columns: ", cols)



Pandas version = 2.1.0

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  househol

Question 3: Select columns with missing data *

In [2]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

Question 4: Number of unique values in the 'ocean_proximity' column *

In [3]:
df[ 'ocean_proximity' ].nunique()

5

Question 5: Average value of the 'median_house_value' for the houses near the bay

In [4]:
#df[ 'median_house_value' ]

In [5]:
df[ df['ocean_proximity'] == 'NEAR BAY' ]['median_house_value'].mean()

259212.31179039303

Question 6
    Calculate the average of total_bedrooms column in the dataset.
    Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
    Now, calculate the average of total_bedrooms again.
    Has it changed?


In [6]:
#avg_total_bedrooms = df[ 'total_bedrooms' ].mean( skipna=False )
#df[ 'total_bedrooms' ] = df[ 'total_bedrooms' ].astype(float)
originalDF = df
df[ 'total_bedrooms' ] = pd.to_numeric( df[ 'total_bedrooms' ] , errors='coerce')
avg_total_bedrooms = df[ 'total_bedrooms' ].mean()
print( "Average of total_bedrooms BEFORE fillna() = {:.3f}".format( avg_total_bedrooms ) )

originalDF[ 'total_bedrooms' ] = originalDF[ 'total_bedrooms' ].fillna( "0" )
originalDF[ 'total_bedrooms' ] = pd.to_numeric( originalDF[ 'total_bedrooms' ] )
avg_total_bedrooms = originalDF[ 'total_bedrooms' ].mean()
print( "Average of total_bedrooms AFTER fillna() = {:.3f}".format( avg_total_bedrooms ) )

#df = df.fillna( "" )
#avg_total_bedrooms = df[ 'total_bedrooms' ].mean()
#print( "Average of total_bedrooms AFTER fillna() = {}".format( avg_total_bedrooms) )
#df.isnull().sum()

Average of total_bedrooms BEFORE fillna() = 537.871
Average of total_bedrooms AFTER fillna() = 532.476


Question 7

    Select all the options located on islands.
    Select only columns housing_median_age, total_rooms, total_bedrooms.
    Get the underlying NumPy array. Let's call it X.
    Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
    Compute the inverse of XTX.
    Create an array y with values [950, 1300, 800, 1000, 1300].
    Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
    What's the value of the last element of w?


In [7]:
#df['ocean_proximity'] .unique()
islandDF = df [ df['ocean_proximity'] == 'ISLAND' ]
#print( islandDF[ ['housing_median_age', 'total_rooms', 'total_bedrooms' ] ])
X = islandDF[ ['housing_median_age', 'total_rooms', 'total_bedrooms' ] ].to_numpy()
print( 'Matrix X' )
print( X )
transpX = X.T
print( 'Matrix X.T Transpose of X' )
print( transpX )
XTX = np.matmul( transpX, X )
print( 'Matrix XTX' )
print( XTX )
invXTX = np.linalg.inv( XTX )
print( 'Matrix invesrse of XTX (invXTX)' )
print( invXTX )
prod2 = np.matmul( invXTX, transpX )
Y = np.array( [950, 1300, 800, 1000, 1300] )
W = np.matmul( prod2, Y )
print( 'Matrix  W' )
print( W )


Matrix X
[[  27. 1675.  521.]
 [  52. 2359.  591.]
 [  52. 2127.  512.]
 [  52.  996.  264.]
 [  29.  716.  214.]]
Matrix X.T Transpose of X
[[  27.   52.   52.   52.   29.]
 [1675. 2359. 2127.  996.  716.]
 [ 521.  591.  512.  264.  214.]]
Matrix XTX
[[9.6820000e+03 3.5105300e+05 9.1357000e+04]
 [3.5105300e+05 1.4399307e+07 3.7720360e+06]
 [9.1357000e+04 3.7720360e+06 9.9835800e+05]]
Matrix invesrse of XTX (invXTX)
[[ 9.19403586e-04 -3.66412216e-05  5.43072261e-05]
 [-3.66412216e-05  8.23303633e-06 -2.77534485e-05]
 [ 5.43072261e-05 -2.77534485e-05  1.00891325e-04]]
Matrix  W
[23.12330961 -1.48124183  5.69922946]
